### ISSUE TITLE
VSCode Feature "1Password: Save in 1Password" does not work

### ISSUE THREAD

**Issue by mircomarahrens** [1Password/op-vscode#100]
# Summary

"1Password: Save in 1Password" does not work.

# Prerequisites

- Tried on Win 11 Pro Build 22621, Win 10 Enterprise Build 19044 and WSL2 Ubuntu 22.04.1 LTS

1. Install 1Password CLI

```PS
PS C:\Users\MircoMarahrens> op --version
2.7.3
```

```bash
$ op --version
2.7.3
```

2. Install VSCode extension "1Password", v1.0.4
3. Connect CLI with app/account
4. "1Password: Choose vault"

# Details

1. Mark item to store
2. "1Password: Save in 1Password"
5. Enter item name
6. Enter field name

# Result

1. Nothing happens. Marked item is not replaced with secret reference. Item is not stored in vault.

**Comment by JackBailey** [comment]
Not sure how you installed but I had the same issue installing from scoop, I uninstalled it and installed via [the powershell command](https://developer.1password.com/docs/cli/get-started/#install) block and it now works fine

**Comment by mircomarahrens** [comment]
@JackBailey Thanks for the hint. I reinstalled the CLI via the [powershell command](https://developer.1password.com/docs/cli/get-started/#install) and **it is working now**.

@jodyheavener I followed the manual installation of <https://developer.1password.com/docs/cli/get-started/#install>. I also tried to get further information from the debug log of the VScode extension but nothing seems to be logged. Anyhow, if I execute "1Password: Choose vault" the authentication part via Windows Hello is working and VScode is asking for my configured vaults. I didn't dig deeper.

**Comment by mircomarahrens** [comment]
As mentioned above. The issue is fixed.

**Comment by brinkokevin** [comment]
> Hey @mircomarahrens, sorry that you're experiencing this issue. I'm curious, is this this the only feature that does not work for you? For example, does Get from 1Password correctly retrieve an item's value?
> 
> I'll also note that you'll need to connect your CLI using Windows Hello PIN or fingerprint. One of those will be needed, as session-based authentication does not work with the extension at this time. After you fill out the two item/field name fields, you should be prompted to authenticate.
> 
> At any rate, it's not ideal that it quietly fails, but I'd like to try and track down exactly how/when the issue occurs.


This issue is still happening, "Get from 1Password" works as expected. "Save in 1Password" doesn't do anything. I attempted to reinstall using powershell command block instead of steps 1...6, but the issue is still happening.
```
$ op --version
2.13.1
```

**Comment by Alkasai** [comment]
> This issue is still happening, "Get from 1Password" works as expected. "Save in 1Password" doesn't do anything. I attempted to reinstall using powershell command block instead of steps 1...6, but the issue is still happening.
> 
> ```
> $ op --version
> 2.13.1
> ```

same here

**Comment by enrij** [comment]
```
PS C:\Users\EnricoBarbieri> op --version
2.17.0
```

Same here... When I click on "Save in 1Password" the Windows Hello is triggered but then an invalid JSON error is raised

`Error executing CLI command: Failed to create item: invalid JSON.`

**Comment by wasdee** [comment]
> ```
> PS C:\Users\EnricoBarbieri> op --version
> 2.17.0
> ```
> 
> Same here... When I click on "Save in 1Password" the Windows Hello is triggered but then an invalid JSON error is raised
> 
> `Error executing CLI command: Failed to create item: invalid JSON.`

observe the same thing on Windows

## My Setup

- use MS. Hello, face
- `op --version`: 2.18,  latest as of today
- 1Password for Windows 8.10.8 (81008047), latest as of today
- VSCode Plugin: 1password, v1.0.4, latest as of today

## Vscode Output
```
["INFO" - 8:56:20 PM] Starting 1Password for VS Code.
["INFO" - 8:56:20 PM] Extension Version: 1.0.4.
["ERROR" - 8:56:42 PM] Error executing CLI command
```

Today is 04/07/2023

**Comment by matt-way** [comment]
Same issue here. Windows 11. `Error executing CLI command: Failed to create item: invalid JSON.`

**Comment by 0GiS0** [comment]
Hi again, I also tested it on Mac and I have a different issue with 2.20 version:

<img width="477" alt="image" src="https://github.com/1Password/op-vscode/assets/175379/2d016113-33bc-42ad-821d-19441c6b616b">

any ideas?

Thank you so much!

**Comment by 1000Phoenix** [comment]
This is still an issue with version 2.27

> > ```
> > PS C:\Users\EnricoBarbieri> op --version
> > 2.17.0
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Same here... When I click on "Save in 1Password" the Windows Hello is triggered but then an invalid JSON error is raised
> > `Error executing CLI command: Failed to create item: invalid JSON.`
> 
> observed the same thing on Windows
> 
> ## My Setup
> * use with MS. Hello, face
> * `op --version`: 2.18,  latest as of today
> * 1Password for Windows 8.10.8 (81008047), latest as of today
> * VSCode Plugin: 1password, v1.0.4, latest as of today
> 
> ## Vscode Output
> ```
> ["INFO" - 8:56:20 PM] Starting 1Password for VS Code.
> ["INFO" - 8:56:20 PM] Extension Version: 1.0.4.
> ["ERROR" - 8:56:42 PM] Error executing CLI command
> ```
> 
> ## Error
> same as @enrij `Error executing CLI command: Failed to create item: invalid JSON.`
> 
> Today is 04/07/2023

**Comment by jodyheavener** [comment]
Hey folks! Just a little ping to let you know that this issue is being investigated. Apologies it's been open for some time now.

**Comment by jodyheavener** [comment]
I've updated the underlying `op-js` package to v0.1.12 in this commit https://github.com/1Password/op-vscode/commit/4a00f0e2857af1496e52f961298310deb38e3fc4. This appears to have resolved the issue. I wish I had a more detailed understanding of why this fixes the issue, but I don't at this time. I'll leave this issue open until the next release is cut.
